# Generated by Django 4.2.7 on 2026-02-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_existing_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='authorized_pages',
            field=models.JSONField(blank=True, default=list, help_text='Les pages auxquelles cet utilisateur a accès', verbose_name='authorized pages'),
        ),
    ]
