# Generated by Django 4.2.7 on 2026-03-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_authorized_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='module',
            field=models.CharField(blank=True, choices=[('production', 'Production'), ('stock', 'Stock'), ('facturation', 'Facturation'), ('orders', 'Commandes'), ('crm', 'CRM'), ('rh', 'Ressources Humaines')], help_text='Module assigné à cet utilisateur', max_length=50, null=True, verbose_name='module'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin', 'Administrateur Module'), ('user', 'Utilisateur Module')], default='user', max_length=20, verbose_name='role'),
        ),
    ]
