# Generated by Django 4.2.7 on 2026-03-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_module_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='module',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('responsable_stock', 'Responsable Stock'), ('responsable_production', 'Responsable Production'), ('responsable_facturation', 'Responsable Facturation'), ('responsable_commandes', 'Responsable Commandes'), ('agent_stock', 'Agent Stock'), ('agent_production', 'Agent Production'), ('employe', 'Employé')], default='employe', max_length=30, verbose_name='role'),
        ),
    ]
