# Generated by Django 4.2.7 on 2026-03-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_module_alter_customuser_role'),
    ]

    operations = [
    ]
