# Generated by Django 6.0.2 on 2026-02-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('optimal', 'Optimal'), ('low', 'Low'), ('out_of_stock', 'Out of stock'), ('rupture', 'Rupture')], default='optimal', max_length=20),
        ),
    ]
