# Generated by Django 4.2.7 on 2026-03-08 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_supplier'),
        ('stock', '0003_supplier_warehouse_category_product_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
