# Generated by Django 4.2.7 on 2026-02-14 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('module', models.CharField(choices=[('stock', 'Stock'), ('crm', 'CRM'), ('facturation', 'Facturation'), ('gmao', 'GMAO'), ('gpao', 'GPAO'), ('rh', 'RH')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critique'), ('high', 'Haute'), ('medium', 'Moyenne'), ('low', 'Basse')], default='medium', max_length=20)),
                ('condition_type', models.CharField(choices=[('threshold', 'Seuil'), ('absence', 'Absence de données'), ('anomaly', "Détection d'anomalie"), ('trend', 'Tendance')], default='threshold', max_length=50)),
                ('threshold_value', models.CharField(blank=True, max_length=255, null=True)),
                ('comparison_operator', models.CharField(choices=[('greater_than', 'Supérieur à'), ('less_than', 'Inférieur à'), ('equal_to', 'Égal à'), ('not_equal', 'Différent de'), ('greater_equal', 'Supérieur ou égal'), ('less_equal', 'Inférieur ou égal')], default='greater_than', max_length=50)),
                ('notification_channels', models.JSONField(default=list, help_text='Liste des canaux de notification')),
                ('recipients', models.JSONField(default=list, help_text='Liste des destinataires')),
                ('schedule', models.CharField(choices=[('immediate', 'Temps réel'), ('hourly', 'Toutes les heures'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='immediate', max_length=20)),
                ('custom_schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-created_at'],
            },
        ),
    ]
