# Generated by Django 6.0.2 on 2026-02-22 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_categories_alert_compare_to_and_more'),
        ('stock', '0002_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='stock.product'),
        ),
    ]
