# Generated by Django 6.0.2 on 2026-03-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationchannelpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannelpreference',
            name='schedule',
            field=models.CharField(choices=[('realtime', 'Temps reel'), ('hourly', 'Toutes les heures'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='realtime', max_length=20),
        ),
    ]
