# Generated by Django 6.0.2 on 2026-03-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notificationchannelpreference_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critique'), ('high', 'Haute'), ('medium', 'Moyenne'), ('low', 'Basse')], default='medium', max_length=20),
        ),
    ]
