# Generated by Django 4.2.7 on 2026-03-05 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('preparing', 'En préparation'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('returned', 'Retournée'), ('cancelled', 'Annulée')], default='pending', help_text='Statut de la commande', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant total de la commande', max_digits=12)),
                ('shipping_address', models.TextField(blank=True, help_text='Adresse de livraison')),
                ('shipping_method', models.CharField(blank=True, help_text='Méthode de livraison (Standard, Express, etc.)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Notes supplémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Date de confirmation', null=True)),
                ('shipped_at', models.DateTimeField(blank=True, help_text="Date d'expédition", null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Date de livraison', null=True)),
                ('customer', models.ForeignKey(help_text='Utilisateur qui a passé la commande', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantité commandée')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Prix unitaire au moment de la commande', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sous-total (quantité × prix)', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Notes sur cet article')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(help_text='Commande', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(help_text='Produit commandé', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='stock.product')),
            ],
            options={
                'verbose_name': 'Élément de commande',
                'verbose_name_plural': 'Éléments de commande',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
