# Generated by Django 4.2.7 on 2026-03-05 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entry', 'Entrée'), ('exit', 'Sortie'), ('transfer', 'Transfert')], help_text='Type de mouvement: Entrée, Sortie ou Transfert', max_length=10)),
                ('quantity', models.PositiveIntegerField(help_text='Quantité du mouvement')),
                ('entry_reason', models.CharField(blank=True, choices=[('purchase', 'Achat'), ('return', 'Retour'), ('adjustment', 'Ajustement'), ('other', 'Autre')], help_text="Raison si c'est une entrée", max_length=20, null=True)),
                ('exit_reason', models.CharField(blank=True, choices=[('sale', 'Vente'), ('loss', 'Perte'), ('production', 'Production'), ('damage', 'Dommage'), ('adjustment', 'Ajustement'), ('other', 'Autre')], help_text="Raison si c'est une sortie", max_length=20, null=True)),
                ('warehouse_from', models.CharField(blank=True, help_text='Entrepôt source (pour transfert)', max_length=255)),
                ('warehouse_to', models.CharField(blank=True, help_text='Entrepôt destination (pour transfert)', max_length=255)),
                ('reference', models.CharField(blank=True, help_text='Numéro de commande, de bon de livraison, etc.', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Notes supplémentaires sur le mouvement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.product')),
                ('responsible', models.ForeignKey(blank=True, help_text='Utilisateur qui a effectué le mouvement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
