# Generated by Django 4.2.7 on 2026-03-08 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0003_supplier_warehouse_category_product_warehouse_and_more'),
        ('stock_movements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='entry_reason',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='exit_reason',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='warehouse_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_movements', to='stock.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='warehouse_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='stock.warehouse'),
        ),
        migrations.CreateModel(
            name='StockExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Numéro de bon de sortie', max_length=100, unique=True)),
                ('exit_type', models.CharField(choices=[('delivery_note', 'Bon de sortie'), ('customer_delivery', 'Livraison client')], default='delivery_note', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('sale', 'Vente'), ('production', 'Production'), ('loss', 'Perte'), ('damage', 'Dommage'), ('adjustment', 'Ajustement'), ('transfer', 'Transfert'), ('other', 'Autre')], default='sale', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('exit_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_exits_prepared', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_exits', to='stock.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_exits', to='stock.warehouse')),
            ],
            options={
                'verbose_name': 'Sortie de stock',
                'verbose_name_plural': 'Sorties de stock',
                'ordering': ['-exit_date'],
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text="Numéro de bon d'entrée", max_length=100, unique=True)),
                ('receipt_type', models.CharField(choices=[('supplier_receipt', 'Réception fournisseur'), ('entry_note', "Bon d'entrée")], default='entry_note', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('purchase', 'Achat fournisseur'), ('return', 'Retour client'), ('adjustment', 'Ajustement'), ('other', 'Autre')], default='purchase', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='stock.product')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries_received', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='stock.supplier')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='stock.warehouse')),
            ],
            options={
                'verbose_name': 'Entrée de stock',
                'verbose_name_plural': 'Entrées de stock',
                'ordering': ['-entry_date'],
            },
        ),
    ]
