# Generated by Django 4.2.7 on 2026-03-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('stock_movements', '0002_remove_stockmovement_entry_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockexit',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_exits', to='orders.order'),
        ),
    ]
