# Generated by Django 4.2.7 on 2026-03-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_add_category_alert_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('product_created', 'Product created'), ('product_updated', 'Product updated'), ('product_deleted', 'Product deleted'), ('user_created', 'User created'), ('category_created', 'Category created'), ('alert_created', 'Alert created'), ('production_order_created', 'Production order created'), ('production_order_updated', 'Production order updated'), ('production_order_deleted', 'Production order deleted'), ('production_issue_reported', 'Production issue reported')], max_length=50),
        ),
    ]
