# Generated by Django 4.2.7 on 2026-03-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_supplier_warehouse_category_product_warehouse_and_more'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('quantity_produced', models.PositiveIntegerField()),
                ('quantity_available', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('in_stock', 'En stock'), ('shipped', 'Expédié'), ('reserved', 'Réservé')], default='in_stock', max_length=20)),
                ('production_date', models.DateField(auto_now_add=True)),
                ('quality_check_passed', models.BooleanField(default=False)),
                ('quality_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finished_product_info', to='stock.product')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_products', to='production.productionorder')),
            ],
            options={
                'verbose_name': 'Produit fini',
                'verbose_name_plural': 'Produits finis',
                'ordering': ['-created_at'],
            },
        ),
    ]
